### ISSUE TITLE
Refactor: Edit/Delete comments, libraries, variables

### ISSUE THREAD

**Issue by lnalice** [lnalice/simple-robot-planner#5]
**[[ to-do ]]**
- [ ] 불필요한 주석, 변수, 라이브러리, 코드 삭제하기
- [ ] 필요한 주석 추가하기 (코드 설명)
- [ ] 쓰지 않는 파일 삭제하기

**[[ 삭제할 파일 목록 ]]**
  - helper/checkLimitVelocity.py
  - publisher/moveBasePub.py
  - test/*
  
**[[ 코드 수정할 파일 목록 ]]**
  - src/*
